#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Satoh-Narumi
# SPDX-License-Identifier: BSD-3-Clause

import sys
import argparse
import subprocess
import shutil

#fetch <オプション> <find>
def find(location,name):
    cmd = ["find", location, "-name", name]
    try:
        location = subprocess.check_output(cmd).decode()
    except subprocess.CalledProcessError:
        return []
    
    lines = location.splitlines()
    return [line for line in lines if line.strip()]
    
    

def main():
    parser = argparse.ArgumentParser(description='指定ディレクトリから同じ名前のファイルをとってくる奴',
                                     prog='fetch',
                                    )
    select_option = parser.add_mutually_exclusive_group(required=True)
    select_option.add_argument('--copy', '-c',action='store_true',help='コピーモード。とってくるファイルを現在地のディレクトリにコピーする')
    select_option.add_argument('--move', '-m',action='store_true',help='移動モード。とってくるファイルを現在地のディレクトリに移動する。')
    parser.add_argument('location',default=None,help='File_location',type=str)
    parser.add_argument('name', default=None,help='filename',type=str)
    args = parser.parse_args()
    
    filelocation = find(args.location, args.name)
    
    for f in filelocation:
        if args.copy:
            shutil.copy2(f, ".")
        elif args.move:
            shutil.move(f, ".")
    
    
if __name__=="__main__":
    main()